export const TEXTS = {
  ROCK: "ROCK",
  PAPER: "PAPER",
  SCISSORS: "SCISSORS",
  SCORE: "SCORE",
  YOU_PICKED: "YOU PICKED",
  HOUSE_PICKED: "THE HOUSE PICKED",
  HOUSE_PICKING: "THE HOUSE PICKING",
  YOU_WON: "YOU WON",
  HOUSE_WON: "THE HOUSE WON",
  DRAW: "IT'S A DRAW",
};

export const SELECT_OPTIONS = {
  ROCK: "ROCK",
  PAPER: "PAPER",
  SCISSORS: "SCISSORS",
};

export const WEAPONS = {
  ROCK: { weakTo: SELECT_OPTIONS.PAPER, strongTo: SELECT_OPTIONS.SCISSORS },
  PAPER: { weakTo: SELECT_OPTIONS.SCISSORS, strongTo: SELECT_OPTIONS.ROCK },
  SCISSORS: { weakTo: SELECT_OPTIONS.ROCK, strongTo: SELECT_OPTIONS.PAPER },
};
