import "./globals.css";
import { Barlow_Semi_Condensed } from "next/font/google";
import GameProvider from "./contexts/GameProvider";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-barlow",
  display: "swap",
});

export const metadata = {
  title: "Play Rock, Paper & Scissors!",
  description: "Author: gorkemarpaci, Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${barlow.variable}`}>
      <body>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
